---
branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: development
    prerelease: true
plugins:
  - "semantic-release-gitmoji"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      message: ":bookmark: Update `package.json` to ${nextRelease.version} [skip release]\n\n${nextRelease.notes}"