---
name: Publish package

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - dev

permissions:
  contents: read # for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Deploy project
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            semantic-release-gitmoji
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
